---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
  namespace: opengauss-discourse
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-server
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: opengauss-discourse
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: web-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/discourse:v1.1.8
        command:
        - /bin/bash
        - -c
        - |
          rails db:migrate
          /sbin/boot
        ports:
        - containerPort: 80
        env:
        - name: DISCOURSE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_database_userrname
        - name: DISCOURSE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_database_password
        - name: DISCOURSE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_db_host
        - name: DISCOURSE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_db_name
        - name: DISCOURSE_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_redis_host
        - name: DISCOURSE_DEVELOPER_EMAILS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_developer_emails
        - name: DISCOURSE_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_hostname
        - name: DISCOURSE_SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_address
        - name: DISCOURSE_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_port
        - name: DISCOURSE_SMTP_USER_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_username
        - name: DISCOURSE_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_password
        - name: DISCOURSE_SMTP_ENABLE_START_TLS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_enable_start_tls
        - name: DISCOURSE_SMTP_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_authentication
        - name: DISCOURSE_NOTIFICATION_EMAIL
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_notification_email
        - name: SENSITIVE_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_domain_name
        - name: SENSITIVE_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_name
        - name: SENSITIVE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_password
        - name: UNICORN_SIDEKIQS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: unicorn_sidekiqs
        resources:
          requests:
            cpu: 500m
            memory: 1500Mi
          limits:
            cpu: 2
            memory: 3000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 5
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: discourse-storage-new
          mountPath: /shared
      volumes:
      - name: discourse-storage-new
        persistentVolumeClaim:
          claimName: discourse-share-volume
