apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- discourse.yaml
- ingress.yaml
- secret.yaml
- namespace.yaml
- pvc.yaml
- redis.yaml
commonAnnotations:
  kubernetes.ops.cluster: opengauss-cce
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: jianglong
  kubernetes.ops.region: hk
namespace: opengauss-discourse
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/discourse
  newTag: v1.7.6
