---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: discourse-secret
  namespace: opengauss-discourse
spec:
  name: discourse-secret
  keysMap:
    discourse_database_userrname:
      path: secrets/data/opengauss/discourse
      key: discourse_database_userrname
    discourse_database_password:
      path: secrets/data/opengauss/discourse
      key: discourse_database_password
    discourse_smtp_username:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_username
    discourse_smtp_password:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_password
    discourse_db_host:
      path: secrets/data/opengauss/discourse
      key: discourse_database_host
    discourse_db_name:
      path: secrets/data/opengauss/discourse
      key: discourse_database
    discourse_developer_emails:
      path: secrets/data/opengauss/discourse
      key: discourse_email
    discourse_hostname:
      path: secrets/data/opengauss/discourse
      key: discourse_host
    discourse_smtp_address:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_address
    discourse_smtp_port:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_port
    discourse_smtp_authentication:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_authentication
    discourse_smtp_enable_start_tls:
      path: secrets/data/opengauss/discourse
      key: discourse_smtp_enable_start_tls
    discourse_notification_email:
      path: secrets/data/opengauss/discourse
      key: discourse_notification_email
    sensitive_domain_name:
      path: secrets/data/opengauss/discourse
      key: sensitive_domain_name
    sensitive_name:
      path: secrets/data/opengauss/discourse
      key: sensitive_name
    sensitive_password:
      path: secrets/data/opengauss/discourse
      key: sensitive_password
    discourse_redis_host:
      path: secrets/data/opengauss/discourse
      key: discourse_redis_host
    unicorn_sidekiqs:
      path: secrets/data/opengauss/discourse
      key: unicorn_sidekiqs
    discourse_maxmind_license_key:
      path: secrets/data/opengauss/discourse
      key: discourse_maxmind_license_key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: discourse-tls
  namespace: opengauss-discourse
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.key:
      key: server.key
      path: secrets/data/opengauss/opengauss-org-tls
  name: discourse-tls
    