---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: discourse-tls
  namespace: opengauss-discourse
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.key:
      key: server.key
      path: secrets/data/opengauss/opengauss-org-tls
  name: discourse-tls
