apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting
  namespace: om
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'om'
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-run-as-user: "1001"
        vault.hashicorp.com/agent-run-as-group: "1001"
        vault.hashicorp.com/secret-volume-path: "/opt/config"
        vault.hashicorp.com/agent-inject-secret-config.ini: 'internal/data/opengauss/om-collect'
        vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
        vault.hashicorp.com/agent-inject-template-config.ini: |
          {{- with secret "internal/data/opengauss/om-collect" -}}  
          {{ .Data.data.Meeting }}
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/template-static-secret-render-interval: 5s
      labels:
        app: meeting
    spec:
      serviceAccount: om
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: infra-seccomp.json
      automountServiceAccountToken: false
      containers:
        - image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.6.59
          name: om-collect
          env:
            - name: APPLICATION_PATH
              value: "/opt/config"
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
      volumes:
        - name: token-vol
          projected:
            sources:
              - serviceAccountToken:
                  audience: api
                  expirationSeconds: 600
                  path: token