apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: swr.cn-north-4.myhuaweicloud.com/om/om-collection
    newTag: feature-zy-meeting-pg-927e0e