---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: easyeditor-secret
  namespace: opengauss-easyeditor
spec:
  name: easyeditor-secret
  keysMap:
    application.yaml:
      path: secrets/data/opengauss/easyeditor
      key: application_yaml