apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-cla
  namespace: opengauss-robot
data:
  config.yaml: |
    config_items:
      - repos:
        - opengauss
        cla_label_yes: opengauss-cla/yes
        cla_label_no: opengauss-cla/no
        check_url: https://clasign.osinfra.cn/api/v1/individual-signing/gitee_opengauss-1614047760000855378
        sign_url: https://clasign.osinfra.cn/sign/gitee_opengauss-1614047760000855378
        faq_url: https://gitcode.com/opengauss/community/blob/master/cla/faq/check-by-author/faq.md
        check_by_committer: true
        lite_pr_committer:
          email: "@noreply.gitcode.com"
          name: GitCode

    user_mark_format: "@"
    placeholder_committer: ""
    placeholder_cla_sign_guide_title: "### CLA Signature Guide"
    placeholder_cla_sign_pass_title: "### CLA Signature Pass"
    comment_command_trigger: "### CLA Signature Manual  \n\nBecause of the network problem, please comment `/check-cla` once again. :pray: "
    comment_pr_no_commits: "### CLA Signature Manual  \n\nThere is no valid commits in the pull request, please check it. "
    comment_some_need_sign: "### CLA Signature Guide  \n\n %s , thanks for your pull request. \n\nThe following commit(s) are not associated with a signed **<font color=green>_Contributor License Agreement (CLA)_</font>**.\n\n%s \n\nTo sign CLA, [**<ins>click here</ins>**](%s). \n\nTo check if your email is configured correctly, refer to the [**<font color=red><ins>_FAQs_</ins></font>**](%s). \n\nOnce you've signed the CLA or updating your email, please comment **`/check-cla`** to revalidate CLA status."
    comment_update_label_failed: "### CLA Signature Manual  \n\nBecause of the CLA label update fail, please comment `/check-cla` once again. :pray: "
    comment_all_signed: "### CLA Signature Pass  \n %s, thanks for your pull request. All authors of the commits have signed the CLA. :+1: "
    sig_info_url: "http://robot-universal-cache-service.opengauss-robot:8888/robot-cache"
    community_name: opengauss
    community_robot_id: opengauss_bot
    invalid_email: "@noreply.gitcode.com"
    invalid_email_message: "the email used in the commit is an invalid email! <br>please check all commits."
    cla_service_failed_message: "the CLA service call failed! please comment `/check-cla` once again."
    comment_unsigned_title: "| Commit | Reason |\n|--|--|"
    comment_unsigned_line: "\n| %s | %s |"
    not_signed_email_message: "the email used in the commit is not linked to a signed CLA! <br>please verify that it matches the email you used when signing the CLA."
    message_individual_version_behind: "the individual CLA content has been updated. <br>[Please click here to re-sign the agreement](https://clasign.osinfra.cn/sign-cla/gitee_opengauss-1614047760000855378/individual-update?email=%s)."
    message_corporation_version_behind: "the corporation CLA content has been updated. <br>Please contact your corporation CLA manager to re-sign the agreement."
    cla_signature_type_corporation: "corporation"
