apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-associate
  namespace: opengauss-robot
data:
  config.yaml: |
    config_items:
    - repos:
      - opengauss
      enable_check_associate_milestone: false
      
    sig_info_url: "http://robot-universal-cache-service.opengauss-robot:8888/robot-cache"
    community_name: opengauss