apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-associate
  namespace: opengauss-robot
data:
  config.yaml: |
    config_items:
    - repos:
        - opengauss/openGauss-server
        - opengauss/openGauss-workbench
        - opengauss/openGauss-OM
        - opengauss/openGauss-connector-jdbc
        - opengauss/CM
        - opengauss/Plugin
        - opengauss/CBB
        - opengauss/DSS
        - opengauss/DCF
        - opengauss/openGauss-embedded
        - opengauss/docs
        - opengauss/DMS
        - opengauss/openGauss-connector-odbc
        - opengauss/openGauss-tools-sql-translator
        - opengauss/QA
        - opengauss/Yat
        - opengauss/cantian
        - opengauss/openGauss-third_party
        - opengauss/openGauss-connector-python-pyog
        - opengauss/openGauss-connector-go-pq
        - opengauss/CM-RestAPI
        - opengauss/compatibility-assessment
        - opengauss/ora-migration-tool
        - opengauss/openGauss-container
        - opengauss/openGauss-DBMind
        - opengauss/openGauss-connector-python-psycopg2
        - opengauss/DCC
        - opengauss/openGauss-tools-datachecker-performance
        - opengauss/debezium
        - opengauss/openGauss-migration-portal
        - opengauss/openGauss-tools-chameleon
      enable_check_associate_milestone: false
      
    sig_info_url: "http://robot-universal-cache-service.opengauss-robot:8888/robot-cache"
    community_name: opengauss
    comment_miss_issue: "### Notice \n @%s , the pull request must be associated with at least one issue. \n If it is already associated with an issue, but the **needs-issue** label also exists, you can comment on **`/check-issue`** to remove this label."
    comment_unset_milestone: "### Notice \n @%s , please select a milestone for the issue. Then, you can use the **/check-milestone** command to remove the **needs-milestone** label"
    community_robot_id: opengauss_bot