---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: opengauss-reproducible
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-reproducible-backend:c018a5375b805e264b9cf67b8dc0b3998abc47aa
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
        - name: HOST_USER
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: host_user
        - name: HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: host_password
        - name: X_ARMOR_BACKEND_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: xarmor_backend_url
        - name: X_ARMOR_BACKEND_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: xarmor_tenant_id
        - name: X_ARMOR_BACKEND_APP_ID
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: xarmor_app_id
        - name: X_ARMOR_BACKEND_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: opengauss-reproducible-secret
              key: xarmor_app_token