---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-reproducible-secret
  namespace: opengauss-reproducible
spec:
  name: opengauss-reproducible-secret
  keysMap:
    host_user:
      path: secrets/data/opengauss/opengauss-reproducible
      key: host_user
    host_password:
      path: secrets/data/opengauss/opengauss-reproducible
      key: host_password
    xarmor_backend_url:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_backend_url
    xarmor_tenant_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_tenant_id
    xarmor_app_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_id
    xarmor_app_token:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_token