---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-jenkins-tls
spec:
  name: opengauss-jenkins-tls
  keysMap:
    ca.crt:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.crt
    tls.crt:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.crt
    tls.key:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.key
