resources:
- deployment.yaml
- service.yaml
- configmap.yaml
namespace: opengauss-robot
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot-universal-welcome
  newTag: develop-lts-0ff37d
