apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-summary
resources:
- opengauss-summary-deployment.yaml
- opengauss-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
- sa.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: c94419415051abe9cf2988b22758fdc76cc8e750
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/summary
  newTag: v1.0.20231228204233
