apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-summary
resources:
- opengauss-summary-deployment.yaml
- opengauss-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
- sa.yaml
- opengauss-summary-ingress.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: b308d046610b7e3a8e8bc8e6dacf6b3725d2a6b4
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/summary
  newTag: v1.0.20240110154505
