apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-summary
resources:
- opengauss-summary-deployment.yaml
- opengauss-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
- sa.yaml
- opengauss-summary-ingress.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: d6d1e6378e682673085a49b8c6b946dbb4932104
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/summary
  newTag: v1.0.20241226203352
