apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-usercenter
  newTag: a39217e6b129f8bc471aaad88880111f61d96aa7
kind: Kustomization
namespace: opengauss-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
- sa.yaml
