apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-usercenter
  newTag: deb83a678981e3c73f3c4bad892da0cc3df0f8e9
kind: Kustomization
namespace: opengauss-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
- sa.yaml
