apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-usercenter
  newTag: 2116d8d9b0924d55aa027158a7070cb0740b6039
kind: Kustomization
namespace: opengauss-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
- sa.yaml
