apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-usercenter
  newTag: 1a1954b7f4a0dbbe0a95b3648840c448463f0f49
kind: Kustomization
namespace: opengauss-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
