apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-usercenter
  newTag: 4d2fa34060c20cbf8fb991f6d5264e798638da85
kind: Kustomization
namespace: opengauss-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
- sa.yaml
