apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-osinfra-tls
  namespace: opengauss-usercenter
spec:
  name: website-osinfra-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-tls
  namespace: opengauss-usercenter
spec:
  name: website-tls
  keysMap:
    ca.crt:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.crt
    tls.crt:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.crt
    tls.key:
      path: secrets/data/opengauss/opengauss-org-tls
      key: server.key