apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-om-collect
  namespace: om
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      common-app: om
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: om-collect
        common-app: om
    spec:
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.5.72
        imagePullPolicy: IfNotPresent
        name: om-collect
        ports:
        - containerPort: 3306
          name: om-collect
          protocol: TCP
        resources:
          requests:
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/om/config.ini
          name: om-collect-secrets-volume
          subPath: config_ini
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: om-collect-secrets-volume
        secret:
          defaultMode: 420
          secretName: meeting-om-secrets
