resources:
- deployment.yaml
- namespace.yaml
- secret.yaml
namespace: om
commonAnnotations:
  kubernetes.ops.cluster: opengauss-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wucaiping
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
