apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: indextool-tls
  namespace: indextool
spec:
  name: indextool-tls
  keysMap:
    ca.crt:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.crt
    tls.crt:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.crt
    tls.key:
      path: secrets/data/opengauss/opengauss-indextool
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-secrets
  namespace: indextool
spec:
  name: doc-search-secrets
  keysMap:
    host:
      path: secrets/data/opengauss/opengauss-indextool
      key: host
    username:
      path: secrets/data/opengauss/opengauss-indextool
      key: username
    password:
      path: secrets/data/opengauss/opengauss-indextool
      key: password
    port:
      path: secrets/data/opengauss/opengauss-indextool
      key: port
    system:
      path: secrets/data/opengauss/opengauss-indextool
      key: system
    depp:
      path: secrets/data/opengauss/opengauss-indextool
      key: depp
    teshost:
      path: secrets/data/opengauss/opengauss-indextool
      key: teshost
    tesusername:
      path: secrets/data/opengauss/opengauss-indextool
      key: tesusername
    tespassword:
      path: secrets/data/opengauss/opengauss-indextool
      key: tespassword
    tesport:
      path: secrets/data/opengauss/opengauss-indextool
      key: tesport
    xarmor_backend_url:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_backend_url
    xarmor_tenant_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_tenant_id
    xarmor_app_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_id
    xarmor_app_token:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_token