apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-osinfra-tls
  namespace: indextool
spec:
  name: doc-search-osinfra-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-secrets
  namespace: indextool
spec:
  name: doc-search-secrets
  keysMap:
    xarmor_backend_url:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_backend_url
    xarmor_tenant_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_tenant_id
    xarmor_app_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_id
    xarmor_backend_app_token:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_backend_app_token
    xarmor_security_enable:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_security_enable
    xarmor_security_root_password:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_security_root_password
    xarmor_security_work_password:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_security_work_password