apiVersion: v1
kind: Service
metadata:
  name: robot-universal-access-service
  namespace: opengauss-robot
spec:
  ports:
  - name: http-port
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: robot-universal-access
  type: ClusterIP