apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneid-server-new
  namespace: opengauss-oneid-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oneid-server-new
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'oneid-server'
        vault.hashicorp.com/agent-inject-secret-application.yml: 'internal/data/infra-common/oneid-server'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/agent-inject-template-application.yml: |  
          {{- with secret "internal/data/infra-common/oneid-server" -}}  
          {{ .Data.data.OneidServer }}
          {{- end }}
      labels:
        app: oneid-server-new
    spec:
      automountServiceAccountToken: false
      serviceAccountName: oneid-server
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-usercenter-server:main-f87369
        imagePullPolicy: IfNotPresent
        name: oneid-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: APPLICATION_PATH
          value: "/vault/secrets/application.yml"
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token