apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-oneid-server
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn1-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: wangweifeng
  kubernetes.ops.region: beijing
resources:
- service.yaml
- deployment.yaml
- secret.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-usercenter-server
  newTag: d7b9fee87e27b75be15bfa1617f262f753479d6c
