---
apiVersion: v1
kind: Service
metadata:
  name: oneid-server-service
  namespace: opengauss-oneid-server
spec:
  ports:
  - name: https-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: oneid-server-new
  sessionAffinity: None
  type: ClusterIP