---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: opengauss-publish-ingress
  namespace: opengauss-repo-verify
spec:
  tls:
  - hosts:
      - publish.opengauss.org
    secretName: opengauss-publish-tls
  rules:
    - host: publish.opengauss.org
      http:
        paths:
          - backend:
              serviceName: post-verification-service
              servicePort: 8080
            path: /