---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-sigs
  namespace: meetingserver
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'opengauss-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: opengauss-meeting
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_merge_opengauss-045ff7
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              - name: MYSQL_TLS_PEM_PATH
                value: /vault/secrets/ca.pem
              - name: TLS_CRT_PATH
                value: /vault/secrets/server.crt
              - name: TLS_KEY_PATH
                value: /vault/secrets/server.key
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py sync_sigs

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: handle-recordings
  namespace: meetingserver
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'opengauss-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/opengauss/opengauss-meeting'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/opengauss/opengauss-meeting" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: opengauss-meeting
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_merge_opengauss-045ff7
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              - name: MYSQL_TLS_PEM_PATH
                value: /vault/secrets/ca.pem
              - name: TLS_CRT_PATH
                value: /vault/secrets/server.crt
              - name: TLS_KEY_PATH
                value: /vault/secrets/server.key
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py handle_recordings
