---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: opengauss-meeting-server-osinfra-ingress
  namespace: meetingserver
spec:
  tls:
    - hosts:
        - meetings-opengauss.osinfra.cn
      secretName: meeting-server-osinfra-tls
  rules:
    - host: meetings-opengauss.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: meeting-service
              servicePort: 8080
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: opengauss-meeting-server-ingress
  namespace: meetingserver
spec:
  tls:
    - hosts:
        - meetings.opengauss.org
      secretName: meeting-server-tls
  rules:
    - host: meetings.opengauss.org
      http:
        paths:
          - backend:
              serviceName: meeting-service
              servicePort: 8080
            path: /

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meeting-server-osinfra-tls
  namespace: meetingserver
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.key:
      key: server.key
      path: secrets/data/infra-common/osinfra-cn
  name: meeting-server-osinfra-tls

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meeting-server-tls
  namespace: meetingserver
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.key:
      key: server.key
      path: secrets/data/opengauss/opengauss-org-tls
  name: meeting-server-tls