apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: opengauss-meeting-server-ingress
  namespace: meetingserver
spec:
  ingressClassName: nginx
  rules:
  - host: meetings.opengauss.org
    http:
      paths:
      - backend:
          service:
            name: meeting-center
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - meetings.opengauss.org
    secretName: meeting-server-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: meeting-center
  namespace: meetingserver
spec:
  ingressClassName: nginx
  rules:
  - host: opengauss-meeting.osinfra.cn
    http:
      paths:
      - backend:
          service:
            name: meeting
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - opengauss-meeting.osinfra.cn
    secretName: meeting-server-osinfra-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: opengauss-meeting-server-osinfra-ingress
  namespace: meetingserver
spec:
  ingressClassName: nginx
  rules:
  - host: meetings-opengauss.osinfra.cn
    http:
      paths:
      - backend:
          service:
            name: meeting-service
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - meetings-opengauss.osinfra.cn
    secretName: meeting-server-osinfra-tls

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meeting-server-osinfra-tls
  namespace: meetingserver
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.key:
      key: server.key
      path: secrets/data/infra-common/osinfra-cn
  name: meeting-server-osinfra-tls

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meeting-server-tls
  namespace: meetingserver
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.key:
      key: server.key
      path: secrets/data/opengauss/opengauss-org-tls
  name: meeting-server-tls