resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- cronjob.yaml
- ingress.yaml
- sa.yaml
commonAnnotations:
  kubernetes.ops.cluster: opengauss-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: liuqi
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meetingserver
