resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- cronjob.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: opengauss-meetingserver
commonAnnotations:
  email: 469227928@qq.com
  owner: liuqi
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meetingserver
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-meeting-server
  newTag: 03dd480daee6db62d22e6772ff1cc64fed04fbe9
