apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-cache
  namespace: opengauss-robot
data:
  config.yaml: |
    repo-save-dir: "/opt/app/repo/tc"
    repo-cached-folder: "community"
    cache-size: 512
    git-platform-domain: gitcode.com
    repo-owner: opengauss
    repo-name: tc
    repo-branch: master
    repo-commit-depth: 1
    repo-fetch-interval: 300
    community-name: opengauss
    repo-of-multi-sig:
      - "opengauss/openGauss-server"
      - "opengauss/openGauss-third_party"
      - "opengauss/openGauss-workbench"
    repo-sig-mapping:
      - "opengauss/openGauss-server:StorageEngine"
      - "opengauss/openGauss-third_party:StorageEngine"
      - "opengauss/openGauss-workbench:Tools"