resources:
- deployment.yaml
- service.yaml
namespace: opengauss-robot
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot-hook-dispatcher
  newTag: develop-lts-12a239
