apiVersion: v1
kind: Service
metadata:
  name: robot-hook-dispatcher-service
  namespace: opengauss-robot
spec:
  ports:
  - name: http-port
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: robot-hook-dispatcher
  type: ClusterIP