---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: jenkins-oauth-secret
  namespace: jenkins
spec:
  name: jenkins-oauth-secret
  keysMap:
    client_id:
      path: secrets/data/opengauss/jenkins-master-cn4
      key: client_id
    client_secret:
      path: secrets/data/opengauss/jenkins-master-cn4
      key: client_secret
    cookie_secret:
      path: secrets/data/opengauss/jenkins-master-cn4
      key: cookie_secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-jenkins
  namespace: jenkins
spec:
  name: opengauss-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/opengauss/jenkins-master-cn4
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/opengauss/jenkins-master-cn4
      key: jenkins-admin-password

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-jenkins-tls
  namespace: jenkins
spec:
  name: opengauss-jenkins-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key