apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-review
  namespace: opengauss-robot
data:
  config.yaml: |
    config_items:
        
      - repos:
          - opengauss/infra
        lgtm_counts_required: 1
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
        
      - repos:
          - opengauss/openGauss-workbench
          - opengauss/openGauss-OM
          - opengauss/openGauss-connector-jdbc
          - opengauss/CM
          - opengauss/Plugin
          - opengauss/CBB
          - opengauss/DSS
          - opengauss/DCF
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - ci-pipeline-success
          - codecheck-success
        labels_not_allow_merge:
          - needs-issue

      - repos:
          - opengauss/openGauss-server
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - ci-pipeline-success
          - codecheck-success
          - lite-ci-success
        labels_not_allow_merge:
          - lite-ci-failed
          - codecheck-failed
          - ci-pipeline-failed
          - needs-issue
  
      - repos:
          - opengauss/openGauss-embedded
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - codecheck-success
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/docs
          - opengauss/DMS
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - ci-pipeline-success
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/tc
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        check_permission_based_on_sig_owners: true
        labels_for_merge:
          - opengauss-cla/yes
  
      - repos:
          - opengauss/openGauss-connector-odbc
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - codecheck-success
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/openGauss-tools-sql-translator
          - opengauss/QA
          - opengauss/Yat
          - opengauss-dev/cantian
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/openGauss-third_party
          - opengauss/openGauss-connector-python-pyog
          - opengauss/openGauss-connector-go-pq
          - opengauss/CM-RestAPI
          - opengauss/compatibility-assessment
          - opengauss/ora-migration-tool
          - opengauss/openGauss-container
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/openGauss-DBMind
          - opengauss/openGauss-connector-python-psycopg2
          - opengauss/CM-RestAPI
          - opengauss/DCC
          - opengauss/openGauss-tools-datachecker-performance
          - opengauss/debezium
          - opengauss/openGauss-migration-portal
          - opengauss/openGauss-tools-chameleon
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - codecheck-success
        labels_not_allow_merge:
          - needs-issue
  
      - repos:
          - opengauss/hcom4db
        lgtm_counts_required: 2
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
          - codecheck-success

      - repos:
          - opengauss
        excluded_repos:
          - opengauss/tc
          - opengauss/openGauss-server
          - opengauss/docs
          - opengauss/openGauss-workbench
          - opengauss/openGauss-tools-sql-translator
        legal_operator: opengauss_bot
        labels_for_merge:
          - opengauss-cla/yes
        lgtm_counts_required: 2

    sig_info_url: "http://robot-universal-cache-service.opengauss-robot:8888/robot-cache"
    community_name: opengauss
    comment_try_squash_again: "### Change Merge Method Failed \n Please comment the command **`/rebase cancel`** to remove the **merge/rebase** label, and then try comment **`/squash`** again."
    comment_try_rebase_again: "### Change Merge Method Failed \n Please comment the command **`/squash cancel`** to remove the **merge/squash** label, and then try comment **`/rebase`** again."
    comment_add_lgtm_by_self: "### Review Code Warning \n @%s , You can't review code by yourself, please contact the maintainers. :astonished: "
    comment_removed_label: "### Review Code Feedback \n- The label **%s** was removed in this pull request. It means that **%s** may need to review the code changes again. :flushed: "
    comment_add_label_successful: "### Review Code Feedback \n- The label **%s** was added to this pull request. It means that **%s** reviewed the code changes. :wave: \n ##### *Tips* \n- If this pull request is not merged while all conditions are met, comment **`/check-pr`** to try again. :smile: "
    comment_add_label_failed: "### Review Code Feedback \n The label **%s** was not added to this pull request by: ***%s***. :wave: \n Please try comment **`/squash`** again."
    comment_no_permission_for_label: "### Review Code Feedback \n ***@%s*** has no permission to %s **%s** label in this pull request. :astonished: \nPlease contact to the collaborators in this repository."
    comment_no_permission_for_lgtm_label: "### Review Code Feedback \n Thanks for your review, @%s, your opinion is very important to us. :wave: \nThe maintainers will consider your advice carefully."
    comment_command_trigger: "### Merge Manual\n @s, Because of the network problem, please comment ***`/%s`*** once again. :pray: "
    comment_clear_label_case_by_pr_update: "### Notice\n New code changes of the pull request are detected and remove these labels ***%s***. :flushed: "
    comment_clear_label_case_by_reopen_pr: "### Notice\n When PR is reopened, remove these labels ***%s***. :flushed: "
    comment_pr_cannot_merge_reason: "### Merge Verification Failed\n@%s, this pr is not mergeable and the reasons are below:\n\n%s"
    comment_msg_missing_labels: "##### *Missing Labels*\n- the pull request needs **%s** label(s)."
    comment_msg_invalid_labels: "##### *Label BackList*\n- the **%s** label(s) caused the pull request to be unable to merge."
    comment_msg_not_enough_lgtm_label: "##### *Not Enough LGTM Labels*\n- the pull request needs **%d** **lgtm** labels and now gets **%d**."
    comment_try_label_again: "### Notice\n the **%s** label's operation log can nof found! please check it."
    comment_no_permission_add_label: "### Notice\n the **%s** user can't add the **%s** label, please fix it or contact the maintainers."
    comment_failed_list_pr_operation_logs: "### Notice\n The corresponding operation log is missing."
    comment_no_ready_tips: "##### *Non-Compliance Label Operations*\n- %s"
    comment_failed_merge_pr: "PR merge failed"
    label_usage_tip_title: "##### *Label Usage Tips*"
    label_usage_tip_detail: "- **%s**: %s"
    label_usage_description:
      - label_name: lgtm
        description: "The code has been reviewed. This can be accomplished by commenting **`/lgtm`**"
      - label_name: approved
        description: "Agree to merge the pull request. This can be accomplished by commenting **`/approve`**"
      - label_name: needs-issue
        description: "Before the PR is merged, it must be associated with the issue."
      - label_name: opengauss-cla/yes
        description: "The code contributor has signed the CLA."
      - label_name: opengauss-cla/no
        description: "The code contributor has not signed the CLA!"
      - label_name: ci-pipeline-success
        description: "The code compilation check job is passed."
      - label_name: codecheck-success
        description: "BThe static code check job is passed."
      - label_name: lite-ci-success
        description: "The code build check job is passed."
      - label_name: lite-ci-failed
        description: "The code build check job failed!"
      - label_name: codecheck-failed
        description: "The static code check job failed!"
      - label_name: ci-pipeline-failed
        description: "The code compilation check job failed!"