apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-docs-osinfra-tls
  namespace: opengauss-docs
spec:
  name: opengauss-docs-osinfra-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-docs-tls
  namespace: opengauss-docs
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/opengauss/opengauss-org-tls
    tls.key:
      key: server.key
      path: secrets/data/opengauss/opengauss-org-tls
  name: opengauss-docs-tls