apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-collect
  namespace: opengauss-userinfo-collect
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userinfo-collect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userinfo-collect
    spec:
      automountServiceAccountToken: false
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.5.82
        imagePullPolicy: IfNotPresent
        name: userinfo-collect
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /var/lib/om/config.ini
          name: opengauss-userinfo-collect-secrets
          subPath: config_ini
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: opengauss-userinfo-collect-secrets
        secret:
          defaultMode: 420
          secretName: opengauss-userinfo-collect-secrets
