apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-collect
  namespace: opengauss-userinfo-collect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfo-collect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'opengauss-userinfo-collect'
        vault.hashicorp.com/agent-inject-secret-config.ini: 'internal/data/infra-common/opengauss-userinfo-collect'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-config.ini: "0400"
        vault.hashicorp.com/agent-run-as-user: "1001"
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/agent-inject-template-config.ini: |  
          {{- with secret "internal/data/infra-common/opengauss-userinfo-collect" -}}  
          {{ .Data.data.config }}
          {{- end }}
        vault.hashicorp.com/secret-volume-path: "/opt/config"
      labels:
        app: userinfo-collect
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccountName: opengauss-userinfo-collect
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.5.82
        imagePullPolicy: IfNotPresent
        name: userinfo-collect
        env:
        - name: APPLICATION_PATH
          value: "/opt/config"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token