resources:
- deployment.yaml
- namespace.yaml
- secret.yaml
namespace: opengauss-userinfo-collect
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn1-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wucaiping
  kubernetes.ops.region: bj
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
