---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mailman-core
  namespace: mail
  labels:
    app: mail-suit-service
  annotations:
    flux.weave.works/tag.mailman-core: semver:~1.0
    flux.weave.works/automated: 'true'
spec:
  serviceName: mail-suit-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mail-suit-service
  template:
    metadata:
      labels:
        app: mail-suit-service
    spec:
      containers:
      - name: mailman-core
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build:291336826605a3042b214075bb9037a52f97058c1673253323
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - mountPath: /opt/mailman/
          name: mailman-core-volume
        env:
        - name: DATABASE_TYPE
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: database_type
        - name: DATABASE_CLASS
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: database_class
        - name: MAILMAN_REST_USER
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailman_core_user
        - name: MAILMAN_REST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailman_core_password
        - name: HYPERKITTY_API_KEY
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: hyperkitty_api_key
        - name: HYPERKITTY_URL
          value: http://mailman-web-service.mail.svc.cluster.local:8000/hyperkitty
        - name: SMTP_HOST
          value: mailman-exim4-service.mail.svc.cluster.local
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: exim4_credential_username
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: exim4_credential_password
        - name: MM_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailcore_mm_hostname
        - name: MAILMAN_REST_PORT
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailcore_rest_port
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailcore_database_url
        - name: MTA
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailcore_mta
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: mailman-secrets
              key: mailcore_smtp_port
      volumes:
      - name: mailman-core-volume
        persistentVolumeClaim:
          claimName: sfs-turbo-mail-data-vol
