---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/opengauss/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/opengauss/mail_secrets
      key: secret_key
    postgres_user:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_user
    postgres_password:
      path: secrets/data/opengauss/mail_secrets
      key: postgres_password
    mailman_admin_email:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_admin_email
    exim4_credential:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential
    exim4_credential_username:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_password:
      path: secrets/data/opengauss/mail_secrets
      key: exim4_credential_splitted_password
    dkim_key:
      path: secrets/data/opengauss/mail_secrets
      key: dkim_key
    mailweb_smtp_host:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_smtp_host
    mailweb_smtp_port:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_smtp_port
    mailweb_django_allowed_hosts:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_django_allowed_hosts
    mailweb_postorius_template_base_url:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_postorius_template_base_url
    mailweb_database_url:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_database_url
    mailweb_server_from_domain:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_server_from_domain
    mailweb_server_web_domain:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_server_web_domain
    mailcore_mm_hostname:
      path: secrets/data/opengauss/mail_secrets
      key: mailcore_mm_hostname
    mailcore_rest_port:
      path: secrets/data/opengauss/mail_secrets
      key: mailcore_rest_port
    mailcore_database_url:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_database_url
    mailcore_mta:
      path: secrets/data/opengauss/mail_secrets
      key: mailcore_mta
    mailcore_smtp_port:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_smtp_port
    database_type:
      path: secrets/data/opengauss/mail_secrets
      key: database_type
    database_class:
      path: secrets/data/opengauss/mail_secrets
      key: database_class
    mailman-api-url:
      path: secrets/data/opengauss/mail_secrets
      key: mailman_api_url
    mailweb_redis_ip:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_redis_ip
    mailweb_redis_port:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_redis_port
    mailweb_redis_password:
      path: secrets/data/opengauss/mail_secrets
      key: mailweb_redis_password
    xarmor_backend_url:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_backend_url
    xarmor_tenant_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_tenant_id
    xarmor_app_id:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_id
    xarmor_app_token:
      path: secrets/data/opengauss/rasp_secret
      key: xarmor_app_token
    DATA_STORAGE_LOCATION:
      path: secrets/data/opengauss/mail_secrets
      key: DATA_STORAGE_LOCATION
    DATA_STORAGE_COMMUNITY:
      path: secrets/data/opengauss/mail_secrets
      key: DATA_STORAGE_COMMUNITY

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets
  namespace: mail
spec:
  name: mailman-cert-secrets
  keysMap:
    server.crt:
      path: secrets/data/opengauss/mail_secrets
      key: server.crt
    server.key:
      path: secrets/data/opengauss/mail_secrets
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-tls-secrets
  namespace: mail
spec:
  name: mailman-tls-secrets
  keysMap:
    opengauss_org_crt:
      path: secrets/data/opengauss/mail_secrets
      key: opengauss_org_crt
    opengauss_org_key:
      path: secrets/data/opengauss/mail_secrets
      key: opengauss_org_key
