## define the config volume for both mail-core & exim4
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sfs-turbo-mail-data-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-sfsturbo
  volumeMode: Filesystem
  volumeName: pv-efs-mail-sfs-turbo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exim-log-data
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk-sas

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailweb-static-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-disk
  volumeMode: Filesystem
