apiVersion: v1
kind: ConfigMap
metadata:
  name: opengauss-configmap
  namespace: opengauss-datastat
data:
  default.conf: |
    # opengauss
    server {
      # listen 443 ssl;
      # server_name localhost;
      # charset utf-8;

      listen 8080;
      server_name datastat.opengauss.org;
      charset utf-8;
      limit_conn perserver 50;
      if ($request_method = 'OPTIONS') {
        return 401;
      }

      location / {
        location /assets {
          # publish every two weeks
          expires 14d;
          add_header Cache-Control public;
        }
        location / {
          add_header Cache-Control no-cache;
        }
        root /usr/share/nginx/html;
        index index.html;
        #   error_page 404 /404.html;
      }

      location /oneid/ {
        proxy_pass https://omapi.osinfra.cn ;
      }

      location /query/ {
        proxy_pass https://dsapi.osinfra.cn/query/ ;
      }

      location /ip-api/ {
        proxy_pass http://ip-api.com/json/;
      }

      location ~ ^/(en|zh) {
        try_files $uri /index.html;
      }

      error_page 500 501 502 503 504 505 /500.html;
      error_page 401 /401.html;
      error_page 404 /404.html;

      location = /401.html {
        root /usr/share/nginx/html;
      }

      location = /404.html {
        root /usr/share/nginx/html;
      }

      location = /500.html {
        root /usr/share/nginx/html;
      }
    }