apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-lite
  namespace: opengauss-etherpad
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: control-etherpad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: control-etherpad
    spec:
      containers:
      - env:
        - name: SKIN_NAME
          valueFrom:
            secretKeyRef:
              key: skin
              name: ether-secret
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              key: env
              name: ether-secret
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              key: db_type
              name: ether-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db_host
              name: ether-secret
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: db_port
              name: ether-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db_name
              name: ether-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: ether-secret
        - name: DB_CHARSET
          valueFrom:
            secretKeyRef:
              key: db_charset
              name: ether-secret
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: ether-secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: db_password
              name: ether-secret
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin_password
              name: ether-secret
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/etherpad:1.8.18
        imagePullPolicy: IfNotPresent
        name: etherpad-lite
        ports:
        - containerPort: 9001
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/etherpad-lite/var
          name: data-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ether-data-vol

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-lite-v2
  namespace: opengauss-etherpad
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: control-etherpad-v2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: control-etherpad-v2
    spec:
      containers:
      - env:
        - name: SKIN_NAME
          valueFrom:
            secretKeyRef:
              key: skin
              name: ether-secret-v2
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              key: env
              name: ether-secret-v2
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              key: db_type
              name: ether-secret-v2
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db_host
              name: ether-secret-v2
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: db_port
              name: ether-secret-v2
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db_name
              name: ether-secret-v2
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: ether-secret-v2
        - name: DB_CHARSET
          valueFrom:
            secretKeyRef:
              key: db_charset
              name: ether-secret-v2
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: ether-secret-v2
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: db_password
              name: ether-secret-v2
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin_password
              name: ether-secret-v2
        - name: ISSUER_AUTHORIZATION_ENDPOINT
          value: "https://id.opengauss.org/oneid/oidc/authorize"
        - name: ISSUER_TOKEN_ENDPOINT
          value: "https://id.opengauss.org/oneid/oidc/token"
        - name: ISSUER_USERINFO_ENDPOINT
          value: "https://id.opengauss.org/oneid/oidc/user"
        - name: ISSUER_ENDPOINT
          value: "https://id.opengauss.org/login"
        - name: ISSUER_JWKS_URI
          value: "https://id.opengauss.org"
        - name: ISSUER_BASE_URL
          value: "https://etherpad.opengauss.org"
        - name: REQUIRE_AUTHENTICATION
          value: "true"
        - name: TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED
          value: "client_secret_post"
        - name: ISSUER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: ISSUER_CLIENT_SECRET
              name: ether-secret-v2
        - name: ISSUER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: ISSUER_CLIENT_ID
              name: ether-secret-v2
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/etherpad:dev-1.8.18-238541
        imagePullPolicy: IfNotPresent
        name: etherpad-lite
        ports:
        - containerPort: 9001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/etherpad-lite/var
          name: data-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ether-data-vol-v2
