resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- pvc.yaml
namespace: opengauss-etherpad
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kubernetes.ops.cluster: infra-hk
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openEuler
  kubernetes.ops.owner: liuyang
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/etherpad
  newTag: openeuler-v1.9.7-40274f
