apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: opengauss-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: muyuying
  kubernetes.ops.region: hk
kind: Kustomization
namespace: opengauss-qa-robot
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/opengauss-qa-robot
  newTag: gauss-bb4ab5
